# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: android

notifications:
  email: false

env:
  global:
    - GRADLE_USER_HOME=${TRAVIS_BUILD_DIR}/.gradle
    - ANDROID_HOME=/usr/local/android-sdk
    - SDK=/usr/local/android-sdk
    - PATH=${GRADLE_USER_HOME}/bin/:${SDK}/:${SDK}/tools/:${SDK}/platform-tools/:${PATH}
    - BUILD_TOOLS='build-tools-21.1.2'
    - MOBI_APP=android
    - WEAR_APP=Wearable
    - ANDROID_SERIAL='emulator-5554'
    - LOG_TAGS='*:E'
    - ADB_INSTALL_TIMEOUT=8 # See https://code.google.com/p/android/issues/detail?id=69735
    #- GRADLE_OPTS="-Xmx768m -Xms256m -Xss4m -Dfile.encoding=UTF-8"

matrix:
  include:
    - env: AVM_TGT=android-18
    - env: AVM_TGT=android-19
    - env: AVM_TGT=android-21
    - env: AVM_TGT='Google Inc.:Google APIs:19' AVM_PKGS=addon-google_apis-google-19
    - env: AVM_TGT='Google Inc.:Google APIs:21' AVM_TAG=google_apis AVM_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
  allow_failures:
    - env: AVM_TGT='Google Inc.:Google APIs:19' AVM_PKGS=addon-google_apis-google-19
    - env: AVM_TGT='Google Inc.:Google APIs:21' AVM_TAG=google_apis AVM_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21

before_install:
  - echo y | android update sdk -u -t platform-tool,tool,extra-android-m2repository,extra-google-m2repository
  - echo y | android update sdk -a -u -t ${BUILD_TOOLS},android-21,sys-img-armeabi-v7a-android-wear-21,${AVM_PKGS:-}
  - adb kill-server; adb start-server

install:
  - echo n | android create avd -f -n "${AVM_NAME:-mobi}" -t "${AVM_TGT:-android-21}" -b
      "${AVM_ABI:-armeabi-v7a}" -g "${AVM_TAG:-default}"
  - echo n | android create avd -f -n "${AVW_NAME:-wear}" -t "${AVW_TGT:-android-21}" -b
      "${AVW_ABI:-armeabi-v7a}" -g "${AVW_TAG:-android-wear}"
  - emulator -avd "${AVM_NAME:-mobi}" -no-skin -no-audio -no-window &
  - emulator -avd "${AVW_NAME:-wear}" -no-skin -no-audio -no-window &
  - adb devices -l; adb wait-for-device; adb get-state; adb get-serialno
  - ./gradlew --version clean compileDebugSources compileDebugTestSources compileReleaseSources

before_script:
  - adb wait-for-device; ./scripts/wait_for_emulator.sh; adb devices; adb shell input keyevent 82 &
  - adb logcat ${LOG_TAGS} | tee logcat.log>/dev/null 2>&1 &

script:
  - ./gradlew :${MOBI_APP:-mobi}:assembleDebug :${MOBI_APP:-mobi}:installDebug
  - ./gradlew :${MOBI_APP:-mobi}:assembleRelease :${MOBI_APP:-mobi}:installRelease
  - ANDROID_SERIAL='emulator-5556'
  - adb wait-for-device; ./scripts/wait_for_emulator.sh; adb devices; adb shell input keyevent 82 &
  - ./gradlew :${WEAR_APP:-wear}:assembleRelease :${WEAR_APP:-wear}:installRelease
  - ANDROID_SERIAL=''
  - ./gradlew connectedCheck

after_script:
  - cat logcat.log; pkill -KILL -f adb