# Copyright 2014 Google Inc. All rights reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: android

notifications:
  email: false

env:
  global:
    - GRADLE_USER_HOME=${TRAVIS_BUILD_DIR}/.gradle
    - ANDROID_HOME=/usr/local/android-sdk
    - SDK=/usr/local/android-sdk
    - PATH=${GRADLE_USER_HOME}/bin/:${SDK}/:${SDK}/tools/:${SDK}/platform-tools/:${PATH}
    - BUILD_TOOLS='build-tools-21.1.2'

matrix:
  include:
    - env: AVD_TARGET=android-15
    - env: AVD_TARGET=android-17
    - env: AVD_TARGET=android-21 AVD_PKGS=sys-img-armeabi-v7a-android-21
    - env: AVD_TARGET='Google Inc.:Google APIs:21' AVD_TAG=google_apis AVD_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
    - env: AVD_TARGET=android-21 AVD_TAG=android-wear
  allow_failures:
    - env: AVD_TARGET='Google Inc.:Google APIs:21' AVD_TAG=google_apis AVD_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
    - env: AVD_TARGET=android-21 AVD_TAG=android-wear

before_install:
  - echo y | android update sdk -u -t platform-tool,tool,android-21,extra-android-m2repository,\
      extra-google-m2repository,android-20,sys-img-armeabi-v7a-android-wear-20
  - echo y | android update sdk -a -u -t $BUILD_TOOLS,${AVD_PKGS:-}

install:
  - echo n | android create avd -f -n test -t "${AVD_TARGET}" -b "${AVD_ABI:-armeabi-v7a}" -g
      "${AVD_TAG:-default}"
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  - ./gradlew androidDependencies
  - ./gradlew clean

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &

script: ./gradlew build connectedCheck
