# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: android

sudo: false

notifications:
  email: false

env:
  global:
    - BUILD_TOOLS='build-tools-21.1.2'

matrix:
  include:
    - env: MOBI_TARGET=android-19
    - env: MOBI_TARGET=android-21
    - env: MOBI_TARGET='Google Inc.:Google APIs:19' MOBI_PKGS=addon-google_apis-google-19
    - env: MOBI_TARGET='Google Inc.:Google APIs:21' MOBI_TAG=google_apis MOBI_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
  allow_failures:
    - env: MOBI_TARGET='Google Inc.:Google APIs:19' MOBI_PKGS=addon-google_apis-google-19
    - env: MOBI_TARGET='Google Inc.:Google APIs:21' MOBI_TAG=google_apis MOBI_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
  fast_finish: true

before_install:
  - echo "Remove unused android components to gain disk space and avoid related issues";
      export IMGS=${ANDROID_HOME}system-images; rm -R ${IMGS}/android-15;
      rm -R ${IMGS}/android-16; rm -R ${IMGS}/android-17; rm -R ${IMGS}/android-18;
      export PFRM=${ANDROID_HOME}platforms; rm -R ${PFRM}/android-15;
      rm -R ${PFRM}/android-16; rm -R ${PFRM}/android-17; rm -R ${PFRM}/android-18;
      rm -R ${ANDROID_HOME}build-tools/21.1.1; rm -R ${ANDROID_HOME}extras || true
  #- export ANDROID_SERIAL='emulator-5554'
  - export MOBI_PATH="${TRAVIS_BUILD_DIR}/avds/${MOBI_NAME:-mobi}"; mkdir avds; echo "$MOBI_PATH"
  - export ANDROID_TMP="${TRAVIS_BUILD_DIR}/avds/temp"; mkdir avds/temp; echo "$ANDROID_TMP"
  #- echo y | android update sdk -u -t platform-tool,tool
  - echo y | android update sdk -u -t extra-android-m2repository,extra-google-m2repository
  - echo y | android update sdk -a -u -t ${BUILD_TOOLS},${MOBI_PKGS:-}

install:
  - echo n | android create avd -f -n "${MOBI_NAME:-mobi}" -t "${MOBI_TARGET:-android-21}" -b
      "${MOBI_ABI:-armeabi-v7a}" -g "${MOBI_TAG:-default}" -p "${MOBI_PATH:-.}" -c 100M
  - android list avd
  - emulator -avd "${MOBI_NAME:-mobi}" -no-skin -no-audio -no-window &
  - adb wait-for-device get-serialno
  - ./gradlew --version
  - ./gradlew clean
  - ./gradlew compileDebugSources compileDebugTestSources compileReleaseSources

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &
  - adb logcat *:W | tee logcat.log>/dev/null 2>&1 &

script:
  - ./gradlew build connectedCheck

after_script:
  - cat logcat.log; pkill -KILL -f adb